### ISSUE TITLE
Unable to load Store Commerce sample extension in Store Commerce In-App

### ISSUE THREAD

**Issue by vkommuri2897** [microsoft/Dynamics365Commerce.InStore#18] opened 2022-08-25 06:50 UTC
![image](https://user-images.githubusercontent.com/111564235/186594424-10b18a8d-3df3-4773-96a2-2e25ccfdb73c.png)
I am trying to debug BarCodeMsrDialogSample but it is failed to load extensions in POS. Below is the error message.

The extension package could not be loaded. Either the extension manifest.json is not included in the extension package or it’s not formatted correctly.

**Comment by Pikhulya** [comment] 2022-09-15 00:04
@vkommuri2897 I assume this topic is a duplicate of the https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/issues/21 and I therefore lean towards resolving this one, please confirm.

**Comment by vkommuri2897** [comment] 2022-09-15 02:33
Hi @Pikhulya  - Here it is different issue. It is missing ScaleUnit installer to run this in IIS hosted local development. If i run this solution in Visual studio code, it is not deploying CRT changes to local retail server. Also i wanted to know if we can add ScaleUnit installer project to same solution and proceed?

**Comment by Pikhulya** [comment] 2022-09-19 22:52
InStore repo helps creating extensions for such In-Store components like Hardware Station and Store Commerce, that is why Scale Unit Installer is not included here but instead is included in the [Scale Unit](https://github.com/microsoft/Dynamics365Commerce.scaleunit) one.

**Comment by vkommuri2897** [comment] 2022-09-20 05:27
Hi @Pikhulya, How can i debug InStore and CommerceRuntime changes together? Can i debug CRT changes with InStore sample in IIS Hosted scaleunit?

**Comment by lukedgr** [comment] 2022-10-06 00:38
Hi @vkommuri2897, you can add a ScaleUnit installer project to your customization solution to make it easier to debug Store Commerce and the CRT extensions together. Below are the documents describing how to debug the Scale Unit and Store Commerce using Visual Studio code.

https://github.com/microsoft/Dynamics365Commerce.ScaleUnit/blob/release/9.40/src/ScaleUnitSample/Readme.md#debugging-1
https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/sc-debug

Visual Studio Code has support for [debugging multiple processes](https://code.visualstudio.com/Docs/editor/debugging#_multitarget-debugging) at the same time (multi-target debugging). Updating the launch configurations in your launch.json based on the info in all the above documents should make it possible to debug Store Commerce and Scale Unit together using Visual Studio Code.

**Closed** 2022-10-06 00:39 UTC
